data_dir: /Users/unac116/Documents/GitHub/mgnns/data/link_prediction/WN18RRv1
exp_dir:  /Users/unac116/Documents/GitHub/mgnns/experiments
use_dummy_constants: false   # options: true | false
encoding_scheme: iclr22 # options: iclr22 | canonical
aggregation_1: max             # options: max | sum 
aggregation_2: max             # options: max | sum 
derivation_threshold: 0.000000001
non_negative_weights: true       # options: true | false
clamping: 0 
